name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      EX_GIX_BUILD: 1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.email "test@example.com"
          git config --global user.name "Test User"
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.0' # Adjust as needed
          otp-version: '27.0' # Adjust as needed
      - name: Cache Mix dependencies
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
      - name: Install Dependencies
        run: mix deps.get
      - name: Run Tests
        run: mix test
